version: 2
jobs:
  build:
    docker:
      - image: golang:1.10-stretch
    working_directory: /go/src/demo
    steps:
      - run: '[ ! -z "$CIRCLE_TAG" ]'
      - checkout
      - run: go get github.com/mitchellh/gox
      - run: gox -ldflags "-X main.version=$CIRCLE_TAG" -output "dist/demo_{{.OS}}_{{.Arch}}"
      - run: ./dist/demo_linux_amd64
      - deploy:
          command: |
            go get github.com/tcnksm/ghr
            ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace $CIRCLE_TAG dist/

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          # trigger the build only on tags
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
